/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public\car.glb -o src\component\car.jsx 
*/
import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('car.glb')
  const { actions, mixer  } = useAnimations(animations, group)
  Object.keys(materials).forEach(key => {
    materials[key].wireframe = props.wireframe;
  });
  console.log(animations

  )
  useEffect(() => {
    if (actions) {
      const action1 = actions['FAN.control.powersuplayAction.001']; 
      const action2 = actions["FAN_Blade_ControlAction.001"];
  
      if (action1) {
        action1.setLoop(THREE.LoopRepeat); 
        action1.timeScale = 1.0; 
        action1.play();
      }
  
      if (action2) {
        action2.setLoop(THREE.LoopOnce); 
        action2.timeScale = 1; 
        action2.play();
      }
    }
  
    return () => {
      if (mixer) {
        mixer.stopAllAction();
      }
    };
  }, [actions, mixer]);
  return (
    <group ref={group} {...props} position={[0,-1,-0.9]} dispose={null}>
      <group name="Scene">
        <group name="Powersurplay001" position={[1.679, 0.833, -0.719]} rotation={[0, 0, -0.739]} scale={3.437}>
          <group name="FANcontrolpowersuplay" position={[-0.001, -0.043, 0.031]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <group name="FANPowersuplay" rotation={[-Math.PI / 2, 0, -Math.PI]}>
              <mesh name="Ebene_1000" geometry={nodes.Ebene_1000.geometry} material={materials.PaletteMaterial003} />
              <mesh name="Ebene_1000_1" geometry={nodes.Ebene_1000_1.geometry} material={materials.RGB} />
            </group>
          </group>
        </group>
        <group name="Wasserkühlung_Kontrolle" position={[0.348, 0.51, 0.302]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437}>
          <group name="FAN_Blade_Control" position={[-0.01, 0.098, 0.113]}>
            <group name="FAN_Blade">
              <mesh name="Fan001" geometry={nodes.Fan001.geometry} material={materials.Fan} />
              <mesh name="Fan001_1" geometry={nodes.Fan001_1.geometry} material={materials.Stecker_kunsstoff} />
              <mesh name="Fan001_2" geometry={nodes.Fan001_2.geometry} material={materials.PaletteMaterial003} />
              <mesh name="Fan001_3" geometry={nodes.Fan001_3.geometry} material={materials.RGB} />
            </group>
          </group>
        </group>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} position={[0.944, -0.056, 0.017]} scale={[1, 1, 2.06]} />
        <mesh name="25Zool_Ramen" geometry={nodes['25Zool_Ramen'].geometry} material={materials.Gehäuse_Grau} position={[0.445, 0.403, -0.478]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Boden_Neu" geometry={nodes.Boden_Neu.geometry} material={materials['Steel_Gebürsted.004']} position={[1.475, 1.028, -0.176]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Bolt001" geometry={nodes.Bolt001.geometry} material={materials.PaletteMaterial002} position={[1.343, 1.129, -0.361]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <group name="Circuitboard001" position={[1.469, 0.997, -0.214]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437}>
          <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials['Platine_front.001']} />
          <mesh name="Cube054_1" geometry={nodes.Cube054_1.geometry} material={materials['Platine_back.001']} />
          <mesh name="Cube054_2" geometry={nodes.Cube054_2.geometry} material={materials['Platine_front.Metal.001']} />
          <mesh name="Cube054_3" geometry={nodes.Cube054_3.geometry} material={materials['Platine_front.Plastik.001']} />
          <mesh name="Cube054_4" geometry={nodes.Cube054_4.geometry} material={materials['Stecker_kunsstoff.002']} />
          <mesh name="Cube054_5" geometry={nodes.Cube054_5.geometry} material={materials['allu.001']} />
          <mesh name="Cube054_6" geometry={nodes.Cube054_6.geometry} material={materials['bLECH.001']} />
          <mesh name="Cube054_7" geometry={nodes.Cube054_7.geometry} material={materials['allu.Black.hell.001']} />
          <mesh name="Cube054_8" geometry={nodes.Cube054_8.geometry} material={materials.PaletteMaterial003} />
        </group>
        <mesh name="Einlass002" geometry={nodes.Einlass002.geometry} material={materials['EK_Schwarz.RTX2080']} position={[1.639, 0.877, 0.095]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Fluid" geometry={nodes.Fluid.geometry} material={materials.PaletteMaterial004} position={[1.327, 1.22, -0.077]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Lichtleiste001" geometry={nodes.Lichtleiste001.geometry} material={materials.RGB} position={[1.486, 1.042, -0.176]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <group name="ASUS_AURA_Controler" position={[1.059, 0.8, -0.482]} rotation={[Math.PI, 0, -2.403]} scale={3.437}>
          <mesh name="seite" geometry={nodes.seite.geometry} material={materials.seite} />
          <mesh name="seite_1" geometry={nodes.seite_1.geometry} material={materials['71gp1zad-1L._AC_SL1500_']} />
          <mesh name="seite_2" geometry={nodes.seite_2.geometry} material={materials['unten-edit']} />
          <mesh name="seite_3" geometry={nodes.seite_3.geometry} material={materials['stirn-edit']} />
          <mesh name="seite_4" geometry={nodes.seite_4.geometry} material={materials.seite5} />
          <mesh name="seite_5" geometry={nodes.seite_5.geometry} material={materials['stirn2-edit.001']} />
          <mesh name="seite_6" geometry={nodes.seite_6.geometry} material={materials['Material.020']} />
          <mesh name="seite_7" geometry={nodes.seite_7.geometry} material={materials.Dreieck} />
          <mesh name="seite_8" geometry={nodes.seite_8.geometry} material={materials.PaletteMaterial005} />
        </group>
        <mesh name="BezierCurve007" geometry={nodes.BezierCurve007.geometry} material={materials.PCI_Power_Cable} position={[1.125, 1.34, 0.199]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="BezierCurve016" geometry={nodes.BezierCurve016.geometry} material={materials.PaletteMaterial006} position={[1.613, 0.635, -0.117]} rotation={[Math.PI, 0, 2.31]} scale={3.437} />
        <mesh name="BezierCurve029" geometry={nodes.BezierCurve029.geometry} material={materials.Stecker_kunsstoff} position={[1.407, 1.015, 0.486]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Fuss02" geometry={nodes.Fuss02.geometry} material={materials['Steel_Gebürsted.001']} position={[1.384, 0.504, -0.96]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <group name="HYPER-ssd-fury" position={[0.434, 0.414, -0.48]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437}>
          <mesh name="hx-product-ssd-fury-rgb-basic-2-zm-lg" geometry={nodes['hx-product-ssd-fury-rgb-basic-2-zm-lg'].geometry} material={materials['hx-product-ssd-fury-rgb-basic-2-zm-lg']} />
          <mesh name="hx-product-ssd-fury-rgb-basic-2-zm-lg_1" geometry={nodes['hx-product-ssd-fury-rgb-basic-2-zm-lg_1'].geometry} material={materials['2002219771A']} />
          <mesh name="hx-product-ssd-fury-rgb-basic-2-zm-lg_2" geometry={nodes['hx-product-ssd-fury-rgb-basic-2-zm-lg_2'].geometry} material={materials['18d7684c514a7df93d21580478c2d858']} />
          <mesh name="hx-product-ssd-fury-rgb-basic-2-zm-lg_3" geometry={nodes['hx-product-ssd-fury-rgb-basic-2-zm-lg_3'].geometry} material={materials['Material.017']} />
          <mesh name="hx-product-ssd-fury-rgb-basic-2-zm-lg_4" geometry={nodes['hx-product-ssd-fury-rgb-basic-2-zm-lg_4'].geometry} material={materials.PaletteMaterial007} />
        </group>
        <group name="Korpus" position={[0.933, 0.915, 0.03]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437}>
          <mesh name="816ioOjeBLL_SL1500_-edit001" geometry={nodes['816ioOjeBLL_SL1500_-edit001'].geometry} material={materials.Oben_Grau} />
          <mesh name="816ioOjeBLL_SL1500_-edit001_1" geometry={nodes['816ioOjeBLL_SL1500_-edit001_1'].geometry} material={materials.PaletteMaterial008} />
          <mesh name="816ioOjeBLL_SL1500_-edit001_2" geometry={nodes['816ioOjeBLL_SL1500_-edit001_2'].geometry} material={materials.Power_knopf} />
          <mesh name="816ioOjeBLL_SL1500_-edit001_3" geometry={nodes['816ioOjeBLL_SL1500_-edit001_3'].geometry} material={materials['Gold.Steel.001']} />
        </group>
        <group name="Mainboard" position={[1.234, 0.673, 0.402]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437}>
          <mesh name="3220476_original_(1)-edit2" geometry={nodes['3220476_original_(1)-edit2'].geometry} material={materials.Mainboard_oben} />
          <mesh name="3220476_original_(1)-edit2_1" geometry={nodes['3220476_original_(1)-edit2_1'].geometry} material={materials['Mainboard_Unten-edit']} />
          <mesh name="3220476_original_(1)-edit2_2" geometry={nodes['3220476_original_(1)-edit2_2'].geometry} material={materials.PaletteMaterial012} />
          <mesh name="3220476_original_(1)-edit2_3" geometry={nodes['3220476_original_(1)-edit2_3'].geometry} material={materials.Battery} />
          <mesh name="3220476_original_(1)-edit2_4" geometry={nodes['3220476_original_(1)-edit2_4'].geometry} material={materials.PaletteMaterial013} />
          <mesh name="3220476_original_(1)-edit2_5" geometry={nodes['3220476_original_(1)-edit2_5'].geometry} material={materials['Mainboard_oben.Plastik']} />
          <mesh name="3220476_original_(1)-edit2_6" geometry={nodes['3220476_original_(1)-edit2_6'].geometry} material={materials['Mainboard_Unten-edit.metal']} />
          <mesh name="3220476_original_(1)-edit2_7" geometry={nodes['3220476_original_(1)-edit2_7'].geometry} material={materials.PaletteMaterial010} />
          <mesh name="3220476_original_(1)-edit2_8" geometry={nodes['3220476_original_(1)-edit2_8'].geometry} material={materials['Mainboard_oben.Metal']} />
          <mesh name="3220476_original_(1)-edit2_9" geometry={nodes['3220476_original_(1)-edit2_9'].geometry} material={materials.PaletteMaterial011} />
          <mesh name="3220476_original_(1)-edit2_10" geometry={nodes['3220476_original_(1)-edit2_10'].geometry} material={materials.Plastik_Schwarz} />
          <mesh name="3220476_original_(1)-edit2_11" geometry={nodes['3220476_original_(1)-edit2_11'].geometry} material={materials.PaletteMaterial009} />
        </group>
        <group name="I7_6900K" position={[1.215, 0.694, 0.632]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437}>
          <mesh name="oben2" geometry={nodes.oben2.geometry} material={materials.I7_9600K_oben2} />
          <mesh name="oben2_1" geometry={nodes.oben2_1.geometry} material={materials.I7_9600K_hinen} />
          <mesh name="oben2_2" geometry={nodes.oben2_2.geometry} material={materials['I7_9600K_oben2.Metal']} />
        </group>
        <mesh name="IO" geometry={nodes.IO.geometry} material={materials['I0zvKoe4okgHkE3s_setting_fff_1_90_end_1000-edit']} position={[1.587, 0.387, 0.409]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="IO_Shield" geometry={nodes.IO_Shield.geometry} material={materials.IO_Shield} position={[1.625, 0.41, 0.652]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Kühlkörper1_Gross" geometry={nodes.Kühlkörper1_Gross.geometry} material={materials.Gusseisen} position={[1.627, 0.5, 0.7]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Sockel_oben1" geometry={nodes.Sockel_oben1.geometry} material={materials.Sokel_oben} position={[1.219, 0.7, 0.632]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Speichersockel002" geometry={nodes.Speichersockel002.geometry} material={materials['3220476_original (1)-edit2.001']} position={[1.423, 0.504, 0.624]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <group name="Tforce_Nighthawk000" position={[1.374, 0.567, 0.612]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437}>
          <mesh name="Tforce_Nighthawk_01-editA004" geometry={nodes['Tforce_Nighthawk_01-editA004'].geometry} material={materials['Tforce_Nighthawk_01-editA']} />
          <mesh name="Tforce_Nighthawk_01-editA004_1" geometry={nodes['Tforce_Nighthawk_01-editA004_1'].geometry} material={materials.TFORCE_Grau} />
          <mesh name="Tforce_Nighthawk_01-editA004_2" geometry={nodes['Tforce_Nighthawk_01-editA004_2'].geometry} material={materials['vorne1.005']} />
          <mesh name="Tforce_Nighthawk_01-editA004_3" geometry={nodes['Tforce_Nighthawk_01-editA004_3'].geometry} material={materials['hinten_1.005']} />
        </group>
        <mesh name="EK_Grosser_Boden" geometry={nodes.EK_Grosser_Boden.geometry} material={materials.EK_GGrau_metal} position={[1.2, 0.762, 0.456]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="EK_Grosser_kühler" geometry={nodes.EK_Grosser_kühler.geometry} material={materials.Certifikat} position={[1.2, 0.762, 0.456]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="EK_Marke" geometry={nodes.EK_Marke.geometry} material={materials['Steel_Gebürsted.Matt']} position={[1.368, 0.657, 0.504]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <group name="Platine_XPG" position={[0.961, 0.934, 0.354]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437}>
          <mesh name="c99c2c5474494ddbbd110601758a9f44-edit" geometry={nodes['c99c2c5474494ddbbd110601758a9f44-edit'].geometry} material={materials.c99platine} />
          <mesh name="c99c2c5474494ddbbd110601758a9f44-edit_1" geometry={nodes['c99c2c5474494ddbbd110601758a9f44-edit_1'].geometry} material={materials['7ae9679384f61-edit']} />
          <mesh name="c99c2c5474494ddbbd110601758a9f44-edit_2" geometry={nodes['c99c2c5474494ddbbd110601758a9f44-edit_2'].geometry} material={materials.c99Aufkleber} />
        </group>
        <mesh name="productGallery87-edit" geometry={nodes['productGallery87-edit'].geometry} material={materials['productGallery87-edit']} position={[0.961, 0.934, 0.354]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <group name="OC_ModulTasten" position={[0.938, 0.812, 1.037]} rotation={[0, 0, -3.095]} scale={3.437}>
          <mesh name="OC_Modul004" geometry={nodes.OC_Modul004.geometry} material={materials['Deckel_grau.Pfeil_glat']} />
          <mesh name="OC_Modul004_1" geometry={nodes.OC_Modul004_1.geometry} material={materials.Deckel_grau} />
          <mesh name="OC_Modul004_2" geometry={nodes.OC_Modul004_2.geometry} material={materials['Display_grau.Tasten']} />
        </group>
        <mesh name="OC_ModulDisplay_only" geometry={nodes.OC_ModulDisplay_only.geometry} material={materials.Display_only} position={[0.938, 0.812, 1.037]} rotation={[0, 0, -3.095]} scale={3.437} />
        <group name="OC_PCB_Modul" position={[0.944, 0.635, 0.986]} rotation={[Math.PI / 2, 0.046, Math.PI]} scale={3.437}>
          <mesh name="OC_PCB_Modul_1" geometry={nodes.OC_PCB_Modul_1.geometry} material={materials.OC_PCB_Modul} />
          <mesh name="OC_PCB_Modul_2" geometry={nodes.OC_PCB_Modul_2.geometry} material={materials['OC_PCB_Modul.Metal']} />
        </group>
        <group name="Powersurplay" position={[1.398, 0.883, -0.762]} rotation={[0, 0, -0.739]} scale={3.437}>
          <mesh name="29113988013" geometry={nodes['29113988013'].geometry} material={materials['Gehäuse_grau.Stecker']} />
          <mesh name="29113988013_1" geometry={nodes['29113988013_1'].geometry} material={materials['Gehäuse_grau.Stecker.rOT']} />
          <mesh name="29113988013_2" geometry={nodes['29113988013_2'].geometry} material={materials['Gehäuse_grau.Front']} />
          <mesh name="29113988013_3" geometry={nodes['29113988013_3'].geometry} material={materials['Gehäuse_grau.Folie']} />
          <mesh name="29113988013_4" geometry={nodes['29113988013_4'].geometry} material={materials['Gehäuse_grau.Stecker.metal']} />
          <mesh name="29113988013_5" geometry={nodes['29113988013_5'].geometry} material={materials.Platine_lehr} />
          <mesh name="29113988013_6" geometry={nodes['29113988013_6'].geometry} material={materials['Material.003']} />
          <mesh name="29113988013_7" geometry={nodes['29113988013_7'].geometry} material={materials['23700007.002']} />
          <mesh name="29113988013_8" geometry={nodes['29113988013_8'].geometry} material={materials.PaletteMaterial015} />
          <mesh name="29113988013_9" geometry={nodes['29113988013_9'].geometry} material={materials['Gehäuse_grau.002']} />
          <mesh name="29113988013_10" geometry={nodes['29113988013_10'].geometry} material={materials.PaletteMaterial014} />
          <mesh name="29113988013_11" geometry={nodes['29113988013_11'].geometry} material={materials.PaletteMaterial016} />
        </group>
        <mesh name="BezierCurve000" geometry={nodes.BezierCurve000.geometry} material={materials.PaletteMaterial017} position={[0.169, 2.023, 0.68]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="BezierCurve005" geometry={nodes.BezierCurve005.geometry} material={materials.Flachband_Kabel} position={[1.409, 0.629, 0.219]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="FAN_Blade001" geometry={nodes.FAN_Blade001.geometry} material={materials.Fan} position={[0.635, 0.773, 0.219]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="FAN_Blade003" geometry={nodes.FAN_Blade003.geometry} material={materials['RGB.001']} position={[0.635, 0.773, -0.608]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Radiator" geometry={nodes.Radiator.geometry} material={materials.PaletteMaterial018} position={[0.692, 0.72, 0.017]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <group name="stecker" position={[1.586, 0.892, -0.474]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437}>
          <mesh name="stecker_1" geometry={nodes.stecker_1.geometry} material={materials['serveimage-edit (1)']} />
          <mesh name="stecker_2" geometry={nodes.stecker_2.geometry} material={materials['Material.000']} />
        </group>
        <mesh name="Stecker2001" geometry={nodes.Stecker2001.geometry} material={materials['Flachband_Kabel.001']} position={[1.397, 0.609, 0.077]} rotation={[-Math.PI / 2, 0.739, -Math.PI]} scale={3.437} />
        <mesh name="Water_cooler_pump" geometry={nodes.Water_cooler_pump.geometry} material={materials.EK_Pump_Sticker} position={[0.348, 0.51, 0.49]} rotation={[-Math.PI / 2, -0.832, -Math.PI]} scale={3.437} />
        <mesh name="Mecanum_wheel_BORBET-B" geometry={nodes['Mecanum_wheel_BORBET-B'].geometry} material={materials['Stahl.001']} position={[2.23, 0.136, 1.172]} scale={3.232} />
        <mesh name="Mecanum_wheel_Axis-Bold" geometry={nodes['Mecanum_wheel_Axis-Bold'].geometry} material={materials.PaletteMaterial001} position={[2.23, 0.136, 1.172]} scale={3.232} />
      </group>
    </group>
  )
}

useGLTF.preload('car.glb')
